services:
  explo:
    image: ghcr.io/lumepart/explo:latest
    restart: unless-stopped
    container_name: explo
    ports:
      - "7288:7288"
    volumes:
      - /volume1/docker/explo/config:/opt/explo/config
      - /volume1/music/explo:/data/
      - /volume1/docker/slskd/downloads:/slskd/
    environment:
      - PUID=1000
      - PGID=10
      - TZ=America/Lima
      - WEB_UI=true

services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=10
      - TZ=America/Lima
    volumes:
      - /volume1/docker/lidarr:/config
      - /volume1/music:/music
      - /volume1/docker/slskd/downloads:/downloads
    ports:
      - 8686:8686

services:
  multi-scrobbler:
    image: foxxmd/multi-scrobbler:latest
    container_name: multi-scrobbler
    restart: unless-stopped

    ports:
      - "9078:9078"

    environment:
      - PUID=1000
      - PGID=10
      - TZ=America/Lima

      # Plex - Source
      - PLEX_URL=http://[IP_ADDRESS]
      - PLEX_TOKEN=<plex token>
      - PLEX_ID=plex

      # ListenBrainz - Client
      - LZ_USER=123stbn
      - LZ_TOKEN=<listenbrainz token>
      - LZ_ID=listenbrainz

      # MusicBrainz
      - MB_PRESETS=default,sensible,native
      - PLEX_TRANSFORMS=musicbrainz

    volumes:
      - /volume1/docker/multi-scrobbler/config:/config

services:
  plex:
    image: ghcr.io/linuxserver/plex:latest
    container_name: Plex
    hostname: plex
    network_mode: host
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:32400/identity"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - /volume1/docker/plex:/config:rw
      - /volume1/Media:/media:ro
      - /volume1/music:/music:ro
    environment:
      TZ: America/Lima
      PUID: 1000
      PGID: 10
      VERSION: public
      PLEX_CLAIM:  <plex claim>
    restart: on-failure:5

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=10
      - TZ=America/Lima
    volumes:
      - /volume1/docker/prowlarr:/config
    ports:
      - 9696:9696

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=10
      - TZ=America/Lima
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /volume1/docker/qbittorrent:/config
      - /volume1/docker/slskd/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp

services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    user: "1000:10"
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_SLSK_USERNAME=<this can be ramdom or generic>
      - SLSKD_SLSK_PASSWORD=<this can be ramdom or generic>
      - SLSKD_API_KEY=<SLSKD_API_KEY>
      - SLSKD_DOWNLOADS_DIR=/downloads
    volumes:
      - /volume1/docker/slskd:/app
      - /volume1/docker/slskd/downloads:/downloads
    restart: always
